Update to axum 0.7
davidpdrsn/axum-typed-websockets pull request #6
Opened 2023-12-01 21:19 UTC by rakshith-ravi

2023-12-02 11:10 UTC, davidpdrsn requested changes
Thanks!

2023-12-02 11:10 UTC, davidpdrsn commented on CHANGELOG.md
> +
This is not released yet so:

```suggestion
- Update to axum 0.7 ([#6])

[#6]: https://github.com/davidpdrsn/axum-typed-websockets/pull/6

# 0.5.0 (15. April, 2023)

```

2023-12-02 11:10 UTC, davidpdrsn commented on Cargo.toml
> +version = "0.6.0"
Please don't bump this. I'll do that when I make a release.

Not sure why it says 0.4 when the published version is 0.5. I suppose I forgot to push some commits.

2023-12-03 09:37 UTC, rakshith-ravi commented on Cargo.toml
> +version = "0.6.0"
Sure thing. I'll revert it

2023-12-03 09:40 UTC, rakshith-ravi commented on Cargo.toml
> +version = "0.6.0"
Done. Did a rebase to remove it from history as well

2023-12-10 09:15 UTC, alekangelov commented
hey @davidpdrsn is there anything else that needs to be done? More than happy to get it through to the finish line cheers

2023-12-31 11:35 UTC, davidpdrsn approved these changes

2023-12-31 11:35 UTC, merged

2023-12-31 11:41 UTC, davidpdrsn commented
Sorry for the delay! I just published this in 0.6.0 🎉